#TODO: Spring Cloud config server
clientdetails:
    clientId: foo
    clientSecret: ""
    authorizedGrantTypes: refresh_token, password
    scope: oauth
    accessTokenValiditySeconds: 1800
    
logging:
  level:
    org.springframework.security: DEBUG
    
spring:
    application:
        name: uaa-service

server:
    port: 5060
    
eureka:
    client:
        serviceUrl:
            defaultZone: "http://localhost:5051/eureka/"