spring:
    jpa:
        hibernate:
            ddl-auto: create-drop

server:
    port: 5000
    
kafka:
    servers: kafka:9092

tokenservice:
    checkTokenEndpointUrl: http://uaa-service/oauth/check_token
    clientId: foo
    clientSecret: "" 