spring:
    application:
        name: product-service
    jpa:
        hibernate:
            ddl-auto: create-drop

eureka:
    client:
        serviceUrl:
            defaultZone: "http://localhost:5051/eureka/"

server:
    port: 5000

tokenservice:
    checkTokenEndpointUrl: http://uaa-service/oauth/check_token
    clientId: foo
    clientSecret: "" 