eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:5051/eureka/"

       
zuul:
 routes:
   products:
     path: /api/products/**
     serviceId: PRODUCT-SERVICE
     stripPrefix: false
   oauth:
     path: /oauth/**
     serviceId: UAA-SERVICE
     sensitiveHeaders: Cookie,Set-Cookie
     stripPrefix: false